name: Setup Mago
author: nhedger
description: Setup the Mago CLI in GitHub Actions
branding:
  color: yellow
  icon: terminal
inputs:
  token:
    description: GitHub Actions token to authenticate API requests
    required: true
    default: ${{ github.token }}
  version:
    description: The version of the Mago CLI to install
    required: true
    default: ""
  working-directory:
    description: The directory in which the action will look for lockfiles to extract the Mago version from
    required: false
    default: ""
runs:
  using: 'node20'
  main: 'dist/index.mjs'
